namespace GFI_Upgrated.SharedDto.Common;

public sealed record LocalizationSeedItem(string Key, string Value, string? Comment = null);

public static class LocalizationDefaults
{
    public static IReadOnlyList<LocalizationSeedItem> SeedItems { get; } = new[]
    {
        new LocalizationSeedItem("Common.Loading", "Loading...", "Generic loading indicator text."),
        new LocalizationSeedItem("Common.Guest", "Guest", "Guest label in header."),
        new LocalizationSeedItem("Common.User", "User", "Fallback role label in header."),
        new LocalizationSeedItem("Common.Actions.Search", "Search", "Common search action."),
        new LocalizationSeedItem("Common.Actions.Save", "Save", "Common save action."),
        new LocalizationSeedItem("Common.Actions.Reset", "Reset", "Common reset action."),
        new LocalizationSeedItem("Common.Actions.Cancel", "Cancel", "Common cancel action."),
        new LocalizationSeedItem("Common.Actions.Submit", "Submit", "Common submit action."),
        new LocalizationSeedItem("Common.Actions.BackToList", "Back to List", "Back-to-list action."),
        new LocalizationSeedItem("Common.Actions.AddNew", "Add New", "Add new action."),
        new LocalizationSeedItem("Common.Actions.Edit", "Edit", "Edit action."),
        new LocalizationSeedItem("Common.Actions.Delete", "Delete", "Delete action."),
        new LocalizationSeedItem("Common.Actions.Export", "Export", "Export action."),
        new LocalizationSeedItem("Common.Status.Active", "Active", "Active status text."),
        new LocalizationSeedItem("Common.Status.Inactive", "Inactive", "Inactive status text."),
        new LocalizationSeedItem("Common.NotFound", "Sorry, there's nothing at this address.", "Not found route text."),
        new LocalizationSeedItem("Common.AccessDenied", "Access denied.", "Access denied message."),
        new LocalizationSeedItem("Layout.Theme", "Theme", "Theme toggle aria label."),
        new LocalizationSeedItem("Layout.Logout", "Logout", "Logout aria label."),
        new LocalizationSeedItem("Layout.Language", "Language", "Header language selector label."),
        new LocalizationSeedItem("Login.PageTitle", "Login - GFI Upgraded", "Login page title."),
        new LocalizationSeedItem("Login.SystemTitle", "GFI Traceability System", "Login screen title."),
        new LocalizationSeedItem("Login.Subtitle", "Please sign in to your account.", "Login screen subtitle."),
        new LocalizationSeedItem("Login.Username", "Username", "Username field label."),
        new LocalizationSeedItem("Login.Password", "Password", "Password field label."),
        new LocalizationSeedItem("Login.SignIn", "Sign in", "Login submit button."),
        new LocalizationSeedItem("Login.SigningIn", "Signing in...", "Busy state for login."),
        new LocalizationSeedItem("Login.InvalidCredentials", "Invalid username or password.", "Invalid login message."),
        new LocalizationSeedItem("Admin.ResourceEditor.PageTitle", "Resource Editor", "Resource editor page title."),
        new LocalizationSeedItem("Admin.ResourceEditor.Title", "Resource Editor", "Resource editor page heading."),
        new LocalizationSeedItem("Admin.ResourceEditor.ResourcesTab", "Resources", "Resources tab title."),
        new LocalizationSeedItem("Admin.ResourceEditor.LanguagesTab", "Languages", "Languages tab title."),
        new LocalizationSeedItem("Admin.ResourceEditor.SyncDefaults", "Sync Defaults", "Seed action label."),
        new LocalizationSeedItem("Admin.ResourceEditor.SearchPlaceholder", "Search keys or values", "Resource search placeholder."),
        new LocalizationSeedItem("Admin.ResourceEditor.ShowMissing", "Show missing only", "Missing-only filter label."),
        new LocalizationSeedItem("Admin.ResourceEditor.NoResources", "No resource records found.", "Empty state for resources."),
        new LocalizationSeedItem("Admin.ResourceEditor.NoLanguages", "No languages found.", "Empty state for languages."),
        new LocalizationSeedItem("Admin.ResourceEditor.DefaultLanguage", "Default Language", "Default language flag label."),
        new LocalizationSeedItem("Admin.ResourceEditor.CultureName", "Culture Name", "Culture name field label."),
        new LocalizationSeedItem("Admin.ResourceEditor.DisplayName", "Display Name", "Display name field label."),
        new LocalizationSeedItem("Admin.ResourceEditor.Country", "Country", "Country field label."),
        new LocalizationSeedItem("Admin.ResourceEditor.Region", "Region", "Region field label."),
        new LocalizationSeedItem("Admin.ResourceEditor.Key", "Key", "Resource key column label."),
        new LocalizationSeedItem("Admin.ResourceEditor.DefaultValue", "Default Value", "Default value column label."),
        new LocalizationSeedItem("Admin.ResourceEditor.TranslatedValue", "Translated Value", "Translated value column label."),
        new LocalizationSeedItem("Admin.ResourceEditor.Comment", "Comment", "Comment label."),
        new LocalizationSeedItem("Admin.ResourceEditor.UpdatedOn", "Updated On", "Updated on label."),
        new LocalizationSeedItem("Admin.ResourceEditor.LanguageSaved", "Language saved successfully.", "Language save success message."),
        new LocalizationSeedItem("Admin.ResourceEditor.ResourceSaved", "Resource saved successfully.", "Resource save success message."),
        new LocalizationSeedItem("Admin.ResourceEditor.DefaultsSynced", "Default resources synced successfully.", "Defaults sync success message."),
        new LocalizationSeedItem("Admin.Staff.Edit.PageTitle.Add", "Add Staff", "Add staff page title."),
        new LocalizationSeedItem("Admin.Staff.Edit.PageTitle.Edit", "Edit Staff", "Edit staff page title."),
        new LocalizationSeedItem("Admin.Staff.Edit.Subtitle", "Add or edit staff details using the legacy field set.", "Staff edit subtitle."),
        new LocalizationSeedItem("Admin.Staff.Edit.Salutation", "Salutation", "Salutation field label."),
        new LocalizationSeedItem("Admin.Staff.Edit.SelectItem", "Select Item", "Default select item label."),
        new LocalizationSeedItem("Admin.Staff.Edit.FirstName", "First Name", "First name field label."),
        new LocalizationSeedItem("Admin.Staff.Edit.LastName", "Last Name", "Last name field label."),
        new LocalizationSeedItem("Admin.Staff.Edit.StaffNumber", "Staff Number", "Staff number field label."),
        new LocalizationSeedItem("Admin.Staff.Edit.NIN", "NIN", "NIN field label."),
        new LocalizationSeedItem("Admin.Staff.Edit.Dob", "D.O.B", "Date of birth field label."),
        new LocalizationSeedItem("Admin.Staff.Edit.MobileNo", "Mobile No.", "Mobile number field label."),
        new LocalizationSeedItem("Admin.Staff.Edit.EmailPersonal", "Email Personal", "Personal email field label."),
        new LocalizationSeedItem("Admin.Staff.Edit.EmailOfficial", "Email Official", "Official email field label."),
        new LocalizationSeedItem("Admin.Staff.Edit.Gender", "Gender", "Gender field label."),
        new LocalizationSeedItem("Admin.Staff.Edit.Select", "Select", "Select option label."),
        new LocalizationSeedItem("Admin.Staff.Edit.Photo", "Photo", "Photo field label."),
        new LocalizationSeedItem("Admin.Staff.Edit.Status", "Status", "Status field label."),
        new LocalizationSeedItem("Admin.Staff.Edit.HasLogin", "Has Login", "Has login checkbox label."),
        new LocalizationSeedItem("Admin.Staff.Edit.SaveFailed", "Staff save failed.", "Staff save failed message."),
        new LocalizationSeedItem("Store.Brands.List.PageTitle", "Brands", "Brands page title."),
        new LocalizationSeedItem("Store.Brands.List.Title", "Brands", "Brands page heading."),
        new LocalizationSeedItem("Store.Brands.List.Subtitle", "Manage product brands and their details.", "Brands page subtitle."),
        new LocalizationSeedItem("Store.Brands.List.SearchLabel", "Search brands", "Brand search label."),
        new LocalizationSeedItem("Store.Brands.List.BrandName", "Brand Name", "Brand name column."),
        new LocalizationSeedItem("Store.Brands.List.Status", "Status", "Status column."),
        new LocalizationSeedItem("Store.Brands.List.Remarks", "Remarks", "Remarks column."),
        new LocalizationSeedItem("Store.Brands.List.Action", "Action", "Action column."),
        new LocalizationSeedItem("Store.Brands.List.NoRecords", "No brand records found.", "Brands empty state."),
        new LocalizationSeedItem("Store.Brands.List.DeleteConfirm", "Are you sure you want to delete brand: {0}?", "Brand delete confirmation."),
        new LocalizationSeedItem("Store.Brands.List.DeleteSuccess", "Brand deleted successfully.", "Brand delete success."),
        new LocalizationSeedItem("Store.Brands.List.DeleteFailed", "Failed to delete brand.", "Brand delete failed."),
        new LocalizationSeedItem("Store.Brands.List.LoadError", "Unable to load brand records.", "Brand load error."),
        new LocalizationSeedItem("AccessDenied.PageTitle", "Access Denied", "Access denied page title."),
        new LocalizationSeedItem("AccessDenied.Message", "You do not have permission to view this page.", "Access denied page message."),
        new LocalizationSeedItem("Menu.ResourceEditor", "Resource Editor", "Admin menu label for resource editor.")
    };
}
